## ATTENTION TESTBENCH


In [2]:
from pynq import Overlay
import numpy as np
from pynq import Xlnk
from pynq.lib import dma
from scipy.linalg import dft
import matplotlib.pyplot as plt

In [3]:
ol=Overlay('attention.bit')

In [4]:
dma1=ol.axi_dma_0
#dma2=ol.axi_dma_1
#dma1.debug=True
#dma2.debug=True

In [23]:
NUM_SAMPLES = 16*16

tokens = np.array([np.random.randint(0, 16) for i in range(NUM_SAMPLES)])
print(tokens.reshape(16, 16))

[[ 3 10  5 15  5  0  7 10  2  3 15 15  1 11 12  5]
 [ 3  9 10  0  0  8  9 12 14  7  4 14  2  2  9 12]
 [ 3 13 15 10  3 12  6  8 15 12  0  8  1 11  8  6]
 [ 5 14 10 14  9  6  0  9  8  6  3  0  1  9 13  8]
 [14  3  9  2 15  9 10  0  6  8  9  3 13  8  8 15]
 [ 2 10  9  4  7  6 15 15  8 14  8 12 13  3  3  3]
 [13  8  0  8  0 14 15  1 11  0 11  9 10 11 15 10]
 [ 6 11 12  6  7 10  9  0 15 10  7 11 13 13  3  0]
 [11  0 12 15 12  3  0  5 14 12 12 11  2  8 13  2]
 [11 13  7  3 12  1  2 15  5  9  3 14 14 14  9 11]
 [ 1  4 12  8 10  2 11  8  0  6  7  3  0 11  8  7]
 [ 2  8 15  3  4  8  0  2  4  0  7  0  1 15  5  8]
 [ 6  0  2 14  3 14  0 11 12 10 10  5  9  4  0 15]
 [ 2  9  0  6 15  8  0 11 11 11  9  6  5  3  8  9]
 [ 3  8  8  0  0 15  9  3  8  1  5 15 15  3 12  9]
 [ 0  5  8 12  5  9 14  9 15 10  2  9  3 14 12  7]]


In [24]:
xlnk = Xlnk()
in_r = xlnk.cma_array(shape=(NUM_SAMPLES,), dtype=np.int32) 
out_r = xlnk.cma_array(shape=(NUM_SAMPLES,), dtype=np.int32) 

np.copyto(in_r, tokens)


In [25]:

dft_ip = ol.attention_0
dft_ip.write(0x10,1)
# Start the DMA send and recv channels.
dma1.recvchannel.start()
dma1.sendchannel.start()

dma1.sendchannel.transfer(in_r)
dma1.sendchannel.wait()
print("In1")

dma1.recvchannel.transfer(out_r)
dma1.recvchannel.wait()
print("Out1")






In1
Out1


In [26]:
print(out_r.reshape(16, 16))

[[ 0 10  8  3  4  4  8  3  6  3  8  5  5  9  1  4]
 [ 0 10  8  3  4  4  8  3  6  3  8  5  5  9  1  4]
 [ 0  0  5  3  4  6  6  5 12  4 11  5 10  8  0  1]
 [ 0 10  8  3  4  4  8  3  6  3  8  5  5  9  1  4]
 [ 0 10  8  3  4  4  8  3  6  3  8  5  5  9  1  4]
 [ 0 10  8  3  4  4  8  3  6  3  8  5  5  9  1  4]
 [ 0 10  8  3  4  4  8  3  6  3  8  5  5  9  1  4]
 [ 0 10  8  3  4  4  8  3  6  3  8  5  5  9  1  4]
 [ 0 12  8  7  8  5 10  9 11  5 14  6 14 11  1  2]
 [ 0 15 11  9  6  7 15  1 12  3 10 11 11  9  4  3]
 [ 0 12  8  7  8  5 10  9 11  5 14  6 14 11  1  2]
 [ 0  0  5  3  4  6  6  5 12  4 11  5 10  8  0  1]
 [ 0 10  8  3  4  4  8  3  6  3  8  5  5  9  1  4]
 [ 0 10  8  3  4  4  8  3  6  3  8  5  5  9  1  4]
 [ 0 10  8  3  4  4  8  3  6  3  8  5  5  9  1  4]
 [ 0 10  8  3  4  4  8  3  6  3  8  5  5  9  1  4]]
